[package]

name = "seabirdsbreakfast"
version = "0.0.1"
authors = ["Sven Nilsen <bvssvni@gmail.com>"]

[dependencies.piston]

git = "https://github.com/pistondevelopers/piston"

[dependencies.sdl2_mixer]

git = "https://github.com/andelf/rust-sdl2_mixer"

[dependencies]

sdl2 = "*"

